//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Cotecna.Vestalis.Core {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Form {
        
        private FormSection[] sectionsField;
        
        private FormRules rulesField;
        
        private string nameField;
        
        private string captionTitleField;
        
        private string captionBreadcrumbsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Section", IsNullable=false)]
        public FormSection[] Sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
            }
        }
        
        /// <remarks/>
        public FormRules Rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CaptionTitle {
            get {
                return this.captionTitleField;
            }
            set {
                this.captionTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CaptionBreadcrumbs {
            get {
                return this.captionBreadcrumbsField;
            }
            set {
                this.captionBreadcrumbsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormSection {
        
        private FormSectionElement[] formElementsField;
        
        private string captionField;
        
        private string legendField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Element", IsNullable=false)]
        public FormSectionElement[] FormElements {
            get {
                return this.formElementsField;
            }
            set {
                this.formElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Legend {
            get {
                return this.legendField;
            }
            set {
                this.legendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormSectionElement {
        
        private string identifierField;
        
        private string defaultValueField;
        
        private bool isDataGridVisibleField;
        
        private bool isFilterVisibleField;
        
        private bool isVisibleClientField;
        
        private bool isInspectionReportVisibleField;
        
        private bool isOrderIdentifierField;
        
        public FormSectionElement() {
            this.isDataGridVisibleField = false;
            this.isFilterVisibleField = false;
            this.isVisibleClientField = true;
            this.isInspectionReportVisibleField = false;
            this.isOrderIdentifierField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDataGridVisible {
            get {
                return this.isDataGridVisibleField;
            }
            set {
                this.isDataGridVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsFilterVisible {
            get {
                return this.isFilterVisibleField;
            }
            set {
                this.isFilterVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsVisibleClient {
            get {
                return this.isVisibleClientField;
            }
            set {
                this.isVisibleClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsInspectionReportVisible {
            get {
                return this.isInspectionReportVisibleField;
            }
            set {
                this.isInspectionReportVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsOrderIdentifier {
            get {
                return this.isOrderIdentifierField;
            }
            set {
                this.isOrderIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormRules {
        
        private FormRulesDateIntervalRule dateIntervalRuleField;
        
        private FormRulesDefaultValueDependentOnCatalogue defaultValueDependentOnCatalogueField;
        
        private FormRulesSummatoryRule summatoryRuleField;
        
        /// <remarks/>
        public FormRulesDateIntervalRule DateIntervalRule {
            get {
                return this.dateIntervalRuleField;
            }
            set {
                this.dateIntervalRuleField = value;
            }
        }
        
        /// <remarks/>
        public FormRulesDefaultValueDependentOnCatalogue DefaultValueDependentOnCatalogue {
            get {
                return this.defaultValueDependentOnCatalogueField;
            }
            set {
                this.defaultValueDependentOnCatalogueField = value;
            }
        }
        
        /// <remarks/>
        public FormRulesSummatoryRule SummatoryRule {
            get {
                return this.summatoryRuleField;
            }
            set {
                this.summatoryRuleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormRulesDateIntervalRule {
        
        private string startFieldField;
        
        private string endFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartField {
            get {
                return this.startFieldField;
            }
            set {
                this.startFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndField {
            get {
                return this.endFieldField;
            }
            set {
                this.endFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormRulesDefaultValueDependentOnCatalogue {
        
        private string catalogueFieldField;
        
        private string textFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CatalogueField {
            get {
                return this.catalogueFieldField;
            }
            set {
                this.catalogueFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TextField {
            get {
                return this.textFieldField;
            }
            set {
                this.textFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormRulesSummatoryRule {
        
        private FormRulesSummatoryRuleElement[] formElementsField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Element", IsNullable=false)]
        public FormRulesSummatoryRuleElement[] FormElements {
            get {
                return this.formElementsField;
            }
            set {
                this.formElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FormRulesSummatoryRuleElement {
        
        private string identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
}
