//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Administration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Administration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Administration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add permissions for the user {0}.
        /// </summary>
        internal static string AddPermissionsTitle {
            get {
                return ResourceManager.GetString("AddPermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned roles.
        /// </summary>
        internal static string AssignedRoles {
            get {
                return ResourceManager.GetString("AssignedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business application.
        /// </summary>
        internal static string BusinessApplication {
            get {
                return ResourceManager.GetString("BusinessApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business application *.
        /// </summary>
        internal static string BusinessApplicationMandatory {
            get {
                return ResourceManager.GetString("BusinessApplicationMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one business application.
        /// </summary>
        internal static string BusinessApplicationNotSelected {
            get {
                return ResourceManager.GetString("BusinessApplicationNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha code.
        /// </summary>
        internal static string CaptchaCode {
            get {
                return ResourceManager.GetString("CaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the code shown above.
        /// </summary>
        internal static string CaptchaValue {
            get {
                return ResourceManager.GetString("CaptchaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business application.
        /// </summary>
        internal static string CatalogueAdministrationGridColumnApplication {
            get {
                return ResourceManager.GetString("CatalogueAdministrationGridColumnApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue Name.
        /// </summary>
        internal static string CatalogueAdministrationGridColumnCatalogueName {
            get {
                return ResourceManager.GetString("CatalogueAdministrationGridColumnCatalogueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an application in the search criteria to filter the list of catalogs. If you don’t select anything, all catalog lists is retrieved..
        /// </summary>
        internal static string CatalogueAdministrationInstruction {
            get {
                return ResourceManager.GetString("CatalogueAdministrationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue configuration.
        /// </summary>
        internal static string CatalogueAdministrationTitle {
            get {
                return ResourceManager.GetString("CatalogueAdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the mandatory fields to create a new category. After that please click on save button for create the new catalogue..
        /// </summary>
        internal static string CatalogueEditNewInstruction {
            get {
                return ResourceManager.GetString("CatalogueEditNewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue management.
        /// </summary>
        internal static string CatalogueIndexBreadCrumb {
            get {
                return ResourceManager.GetString("CatalogueIndexBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue item.
        /// </summary>
        internal static string CatalogueItem {
            get {
                return ResourceManager.GetString("CatalogueItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue items.
        /// </summary>
        internal static string CatalogueItems {
            get {
                return ResourceManager.GetString("CatalogueItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue management.
        /// </summary>
        internal static string CatalogueManagementTitle {
            get {
                return ResourceManager.GetString("CatalogueManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue Management.
        /// </summary>
        internal static string CatalogueMenu {
            get {
                return ResourceManager.GetString("CatalogueMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the mandatory fields to create a new value. After that please click in save button..
        /// </summary>
        internal static string CatalogueValueAdministrationInstruction {
            get {
                return ResourceManager.GetString("CatalogueValueAdministrationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue value administration.
        /// </summary>
        internal static string CatalogueValueAdministrationTitle {
            get {
                return ResourceManager.GetString("CatalogueValueAdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CatalogueValueGridColumnDescription {
            get {
                return ResourceManager.GetString("CatalogueValueGridColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string CatalogueValueGridColumnValue {
            get {
                return ResourceManager.GetString("CatalogueValueGridColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue value list.
        /// </summary>
        internal static string CatalogueValueList {
            get {
                return ResourceManager.GetString("CatalogueValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        internal static string ChangedPasswordConfirmationParagraph1 {
            get {
                return ResourceManager.GetString("ChangedPasswordConfirmationParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go to the login screen and log on with your username and your new password.
        /// </summary>
        internal static string ChangedPasswordConfirmationParagraph2 {
            get {
                return ResourceManager.GetString("ChangedPasswordConfirmationParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect, please verify your information.
        /// </summary>
        internal static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one client.
        /// </summary>
        internal static string ClientNotSelected {
            get {
                return ResourceManager.GetString("ClientNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed name.
        /// </summary>
        internal static string CompletedName {
            get {
                return ResourceManager.GetString("CompletedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please mark the business application as default.
        /// </summary>
        internal static string DefaultAppMandatory {
            get {
                return ResourceManager.GetString("DefaultAppMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this catalogue?.
        /// </summary>
        internal static string DeleteCatalogueCategoryMessage {
            get {
                return ResourceManager.GetString("DeleteCatalogueCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this catalogue value?.
        /// </summary>
        internal static string DeleteCatalogueValueMessage {
            get {
                return ResourceManager.GetString("DeleteCatalogueValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the user permission?.
        /// </summary>
        internal static string DeletePermissionMessage {
            get {
                return ResourceManager.GetString("DeletePermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected User?.
        /// </summary>
        internal static string DeleteUserConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteUserConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the permission the user ?.
        /// </summary>
        internal static string DeleteUserMessage {
            get {
                return ResourceManager.GetString("DeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the permission for the user {0}.
        /// </summary>
        internal static string EditPermissionsTitle {
            get {
                return ResourceManager.GetString("EditPermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permission.
        /// </summary>
        internal static string EditPermisssionButton {
            get {
                return ResourceManager.GetString("EditPermisssionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a valid email address.
        /// </summary>
        internal static string EmailFormatNotValid {
            get {
                return ResourceManager.GetString("EmailFormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wirte a e-mail address.
        /// </summary>
        internal static string EmailMandatory {
            get {
                return ResourceManager.GetString("EmailMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captcha code isn&apos;t correct..
        /// </summary>
        internal static string ForgetPasswordCaptchaNotValid {
            get {
                return ResourceManager.GetString("ForgetPasswordCaptchaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write an e-mail.
        /// </summary>
        internal static string ForgetPasswordEmailNotValid {
            get {
                return ResourceManager.GetString("ForgetPasswordEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error changing the password.
        /// </summary>
        internal static string ForgetPasswordGeneralError {
            get {
                return ResourceManager.GetString("ForgetPasswordGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed sucessfully.
        /// </summary>
        internal static string ForgetPasswordSubjectConfirEmail {
            get {
                return ResourceManager.GetString("ForgetPasswordSubjectConfirEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        internal static string ForgetPasswordSubjectEmail {
            get {
                return ResourceManager.GetString("ForgetPasswordSubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user was not found, please verify your information..
        /// </summary>
        internal static string ForgetPasswordUserNotFound {
            get {
                return ResourceManager.GetString("ForgetPasswordUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a full name.
        /// </summary>
        internal static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a login name.
        /// </summary>
        internal static string LoginNameRequired {
            get {
                return ResourceManager.GetString("LoginNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length is too short, you have to write at least 6 characters.
        /// </summary>
        internal static string MinLegthPassword {
            get {
                return ResourceManager.GetString("MinLegthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        internal static string NameMandatory {
            get {
                return ResourceManager.GetString("NameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The write the new password.
        /// </summary>
        internal static string NewPassRequired {
            get {
                return ResourceManager.GetString("NewPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New permission.
        /// </summary>
        internal static string NewPersmissionButton {
            get {
                return ResourceManager.GetString("NewPersmissionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission in the business application {0} cannot be deleted..
        /// </summary>
        internal static string NonDeleteMultiplePermissionMessage {
            get {
                return ResourceManager.GetString("NonDeleteMultiplePermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} cannot be deleted..
        /// </summary>
        internal static string NonDeleteMultipleUseMessage {
            get {
                return ResourceManager.GetString("NonDeleteMultipleUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This permission cannot be deleted..
        /// </summary>
        internal static string NonDeletePermissionMessage {
            get {
                return ResourceManager.GetString("NonDeletePermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user cannot be deleted..
        /// </summary>
        internal static string NonDeleteUserMessage {
            get {
                return ResourceManager.GetString("NonDeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords aren&apos;t equals.
        /// </summary>
        internal static string NotEqualPassword {
            get {
                return ResourceManager.GetString("NotEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the old password.
        /// </summary>
        internal static string OldPassRequired {
            get {
                return ResourceManager.GetString("OldPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a password.
        /// </summary>
        internal static string PasswordNotFilled {
            get {
                return ResourceManager.GetString("PasswordNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions list.
        /// </summary>
        internal static string PermissionList {
            get {
                return ResourceManager.GetString("PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of permissions for the user &apos;&apos;{0}&apos;&apos;.
        /// </summary>
        internal static string PermissionTitle {
            get {
                return ResourceManager.GetString("PermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The re-write the new password.
        /// </summary>
        internal static string ReNewPassWordRequired {
            get {
                return ResourceManager.GetString("ReNewPassWordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordButton {
            get {
                return ResourceManager.GetString("ResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail has been sent to your e-mail address allowing you to reset your password..
        /// </summary>
        internal static string ResetPasswordConfirmationParagraph1 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have to check your junk mail box for our message..
        /// </summary>
        internal static string ResetPasswordConfirmationParagraph2 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to login.
        /// </summary>
        internal static string ReturnLogin {
            get {
                return ResourceManager.GetString("ReturnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type new password.
        /// </summary>
        internal static string ReTypeNewPassword {
            get {
                return ResourceManager.GetString("ReTypeNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles and Business applications.
        /// </summary>
        internal static string RolesBusinessAppTitle {
            get {
                return ResourceManager.GetString("RolesBusinessAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one or more roles for the user.
        /// </summary>
        internal static string RolesNotSelected {
            get {
                return ResourceManager.GetString("RolesNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user type.
        /// </summary>
        internal static string SelectedUserTypeNotFilled {
            get {
                return ResourceManager.GetString("SelectedUserTypeNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary password.
        /// </summary>
        internal static string TemporaryPassword {
            get {
                return ResourceManager.GetString("TemporaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the following form to create a user.
        /// </summary>
        internal static string UserConfigurationInstruction {
            get {
                return ResourceManager.GetString("UserConfigurationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please edit the password of the user if you need. The field email and the user type field cannot be modified..
        /// </summary>
        internal static string UserConfigurationInstructionEdit {
            get {
                return ResourceManager.GetString("UserConfigurationInstructionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User configuration.
        /// </summary>
        internal static string UserConfigurationTitle {
            get {
                return ResourceManager.GetString("UserConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists.
        /// </summary>
        internal static string UserCreationError {
            get {
                return ResourceManager.GetString("UserCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  a search criteria to get the list of users. If you don’t select any search criteria, the system retrieves the completed list of users..
        /// </summary>
        internal static string UserManagementInstruction {
            get {
                return ResourceManager.GetString("UserManagementInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        internal static string UserManagementTitle {
            get {
                return ResourceManager.GetString("UserManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UsersMenu {
            get {
                return ResourceManager.GetString("UsersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        internal static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client user.
        /// </summary>
        internal static string UserTypeClient {
            get {
                return ResourceManager.GetString("UserTypeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotecna user.
        /// </summary>
        internal static string UserTypeCotecna {
            get {
                return ResourceManager.GetString("UserTypeCotecna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global administrator.
        /// </summary>
        internal static string UserTypeGlobal {
            get {
                return ResourceManager.GetString("UserTypeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application administrator.
        /// </summary>
        internal static string UserTypeLocal {
            get {
                return ResourceManager.GetString("UserTypeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value *.
        /// </summary>
        internal static string ValueMandatory {
            get {
                return ResourceManager.GetString("ValueMandatory", resourceCulture);
            }
        }
    }
}
