//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InspectionReports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InspectionReports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InspectionReports", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this inspection report ?.
        /// </summary>
        internal static string DeleteInspectionReport {
            get {
                return ResourceManager.GetString("DeleteInspectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete picture(s).
        /// </summary>
        internal static string DeletePictureButton {
            get {
                return ResourceManager.GetString("DeletePictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the inspection report form.  * indicated mandatory fields..
        /// </summary>
        internal static string GeneralInstruction {
            get {
                return ResourceManager.GetString("GeneralInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service order .
        /// </summary>
        internal static string InspectionReportHeaderSeach {
            get {
                return ResourceManager.GetString("InspectionReportHeaderSeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection report.
        /// </summary>
        internal static string InspectionReportTitle {
            get {
                return ResourceManager.GetString("InspectionReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your search criteria:.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish all.
        /// </summary>
        internal static string PublishAll {
            get {
                return ResourceManager.GetString("PublishAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to publish selected inspection report items?.
        /// </summary>
        internal static string PublishAllValidationMessage {
            get {
                return ResourceManager.GetString("PublishAllValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish confirmation.
        /// </summary>
        internal static string PublishConfirmation {
            get {
                return ResourceManager.GetString("PublishConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to publish all inspection reports?.
        /// </summary>
        internal static string PublishConfirmationMessage {
            get {
                return ResourceManager.GetString("PublishConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish selected items.
        /// </summary>
        internal static string PublishSelectedItems {
            get {
                return ResourceManager.GetString("PublishSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        internal static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        internal static string TitleView {
            get {
                return ResourceManager.GetString("TitleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish.
        /// </summary>
        internal static string UnPublish {
            get {
                return ResourceManager.GetString("UnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate all.
        /// </summary>
        internal static string ValidateAll {
            get {
                return ResourceManager.GetString("ValidateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to validate selected inspection report items?.
        /// </summary>
        internal static string ValidateAllValidationMessage {
            get {
                return ResourceManager.GetString("ValidateAllValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate confirmation.
        /// </summary>
        internal static string ValidateConfimation {
            get {
                return ResourceManager.GetString("ValidateConfimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to validate all inspection reports?.
        /// </summary>
        internal static string ValidateConfirmationMessage {
            get {
                return ResourceManager.GetString("ValidateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate selected items.
        /// </summary>
        internal static string ValidateSelectedItems {
            get {
                return ResourceManager.GetString("ValidateSelectedItems", resourceCulture);
            }
        }
    }
}
