//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ServiceOrder", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date must have a value.
        /// </summary>
        internal static string BeginDateValue {
            get {
                return ResourceManager.GetString("BeginDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One User.
        /// </summary>
        internal static string ComboBoxUserDefaultOption {
            get {
                return ResourceManager.GetString("ComboBoxUserDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date must be less than end date.
        /// </summary>
        internal static string DateRule {
            get {
                return ResourceManager.GetString("DateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the service order?.
        /// </summary>
        internal static string DeleteServiceOrder {
            get {
                return ResourceManager.GetString("DeleteServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write only digits.
        /// </summary>
        internal static string DigitsValidationMessage {
            get {
                return ResourceManager.GetString("DigitsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit service order.
        /// </summary>
        internal static string EditServiceOrder {
            get {
                return ResourceManager.GetString("EditServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must have a value.
        /// </summary>
        internal static string EndDateValue {
            get {
                return ResourceManager.GetString("EndDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} has incorrect format. The correct format is dd/mm/yyyy.
        /// </summary>
        internal static string ErrorFieldDateIncorrect {
            get {
                return ResourceManager.GetString("ErrorFieldDateIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is greater than {1}.
        /// </summary>
        internal static string ErrorFieldDateRuleEndDate {
            get {
                return ResourceManager.GetString("ErrorFieldDateRuleEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is less than {1}.
        /// </summary>
        internal static string ErrorFieldDateRuleStartDate {
            get {
                return ResourceManager.GetString("ErrorFieldDateRuleStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid number..
        /// </summary>
        internal static string ErrorFieldNumericIncorrect {
            get {
                return ResourceManager.GetString("ErrorFieldNumericIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} doesn&apos;t match with the pattern {1}.
        /// </summary>
        internal static string ErrorFieldRegularExpression {
            get {
                return ResourceManager.GetString("ErrorFieldRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required.
        /// </summary>
        internal static string ErrorFieldRequired {
            get {
                return ResourceManager.GetString("ErrorFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} exceeds the maximum number of characters.
        /// </summary>
        internal static string ErrorFieldTextMaxLength {
            get {
                return ResourceManager.GetString("ErrorFieldTextMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is greater than {1}.
        /// </summary>
        internal static string ErrorFieldTextMaxValue {
            get {
                return ResourceManager.GetString("ErrorFieldTextMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is less than the minimum number of characters.
        /// </summary>
        internal static string ErrorFieldTextMinLength {
            get {
                return ResourceManager.GetString("ErrorFieldTextMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is less than {1}.
        /// </summary>
        internal static string ErrorFieldTextMinValue {
            get {
                return ResourceManager.GetString("ErrorFieldTextMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} has incorrect number of digits.
        /// </summary>
        internal static string ErrorFieldTextNumDigit {
            get {
                return ResourceManager.GetString("ErrorFieldTextNumDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one option for generating the report..
        /// </summary>
        internal static string GenerateReportMessage {
            get {
                return ResourceManager.GetString("GenerateReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate service order report.
        /// </summary>
        internal static string GenerateServiceOrderReport {
            get {
                return ResourceManager.GetString("GenerateServiceOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one or more reports for exporting to excel.
        /// </summary>
        internal static string InspectionReportsChooseInstruction {
            get {
                return ResourceManager.GetString("InspectionReportsChooseInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection reports.
        /// </summary>
        internal static string InspectionReportsChooseTitle {
            get {
                return ResourceManager.GetString("InspectionReportsChooseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the form to order an inspection&amp;nbsp;&amp;nbsp;&amp;nbsp;* indicate mandatory fields.
        /// </summary>
        internal static string InstructionGeneral {
            get {
                return ResourceManager.GetString("InstructionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field. Please enter a value.
        /// </summary>
        internal static string MandatoryFieldValidationMessage {
            get {
                return ResourceManager.GetString("MandatoryFieldValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a value less than {0}.
        /// </summary>
        internal static string MaxValueValidationMessage {
            get {
                return ResourceManager.GetString("MaxValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, at least {0} characters are necessary.
        /// </summary>
        internal static string MinLengthValidationMessage {
            get {
                return ResourceManager.GetString("MinLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a value grater than {0}.
        /// </summary>
        internal static string MinValueValidationMessage {
            get {
                return ResourceManager.GetString("MinValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New service order.
        /// </summary>
        internal static string NewServiceOrder {
            get {
                return ResourceManager.GetString("NewServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write only digists.
        /// </summary>
        internal static string NumbersValidationMessage {
            get {
                return ResourceManager.GetString("NumbersValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a correct input.
        /// </summary>
        internal static string RegularExpressionErrorMessage {
            get {
                return ResourceManager.GetString("RegularExpressionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid value.
        /// </summary>
        internal static string SelectionNotValidMessage {
            get {
                return ResourceManager.GetString("SelectionNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ServiceOrderListSearchSection {
            get {
                return ResourceManager.GetString("ServiceOrderListSearchSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order List.
        /// </summary>
        internal static string ServiceOrderListTitle {
            get {
                return ResourceManager.GetString("ServiceOrderListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your search criteria:.
        /// </summary>
        internal static string ServiceOrderListTitleLegend {
            get {
                return ResourceManager.GetString("ServiceOrderListTitleLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order.
        /// </summary>
        internal static string ServiceOrderMenu {
            get {
                return ResourceManager.GetString("ServiceOrderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order {0}.
        /// </summary>
        internal static string ServiceOrderNumber {
            get {
                return ResourceManager.GetString("ServiceOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders.
        /// </summary>
        internal static string ServiceOrderTitle {
            get {
                return ResourceManager.GetString("ServiceOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the values is different of the expected value.
        /// </summary>
        internal static string SummatoryRule {
            get {
                return ResourceManager.GetString("SummatoryRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the correct 24h time.
        /// </summary>
        internal static string TimeValidadtionMessage {
            get {
                return ResourceManager.GetString("TimeValidadtionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View service order.
        /// </summary>
        internal static string ViewServiceOrder {
            get {
                return ResourceManager.GetString("ViewServiceOrder", resourceCulture);
            }
        }
    }
}
