//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Vestalis.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cotecna.Vestalis.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization cannot be performed because the selected login has no OfficeId. LoginId =.
        /// </summary>
        internal static string LoginWithoutOfficeId {
            get {
                return ResourceManager.GetString("LoginWithoutOfficeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the MessageTemplateDescription resource value.
        /// </summary>
        internal static string MessageTemplateDescription {
            get {
                return ResourceManager.GetString("MessageTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the MessageTemplateResourceNameDescription resource value.
        /// </summary>
        internal static string MessageTemplateResourceNameDescription {
            get {
                return ResourceManager.GetString("MessageTemplateResourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the MessageTemplateResourceTypeNameDescription resource value.
        /// </summary>
        internal static string MessageTemplateResourceTypeNameDescription {
            get {
                return ResourceManager.GetString("MessageTemplateResourceTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toto.
        /// </summary>
        internal static string NodeMapRegistrar {
            get {
                return ResourceManager.GetString("NodeMapRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pwdLastSet.
        /// </summary>
        internal static string pwdLastSet {
            get {
                return ResourceManager.GetString("pwdLastSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the StoredProcedureNameDescription resource value.
        /// </summary>
        internal static string StoredProcedureNameDescription {
            get {
                return ResourceManager.GetString("StoredProcedureNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure Validator (long).
        /// </summary>
        internal static string StoredProcedureValidator_LongText {
            get {
                return ResourceManager.GetString("StoredProcedureValidator_LongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure Validator.
        /// </summary>
        internal static string StoredProcedureValidator_Text {
            get {
                return ResourceManager.GetString("StoredProcedureValidator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredProcedureValidatorNode.
        /// </summary>
        internal static string StoredProcedureValidatorNodeName {
            get {
                return ResourceManager.GetString("StoredProcedureValidatorNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the TagDescription resource value.
        /// </summary>
        internal static string TagDescription {
            get {
                return ResourceManager.GetString("TagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} executing at {1}.
        /// </summary>
        internal static string TraceStamp_Message {
            get {
                return ResourceManager.GetString("TraceStamp_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} executing at {1}.
        /// </summary>
        internal static string TraceStampMessage {
            get {
                return ResourceManager.GetString("TraceStampMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ServiceSecurityContext: could not obtain user credentials.
        /// </summary>
        internal static string WrongSecurityContext {
            get {
                return ResourceManager.GetString("WrongSecurityContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ServiceSecurityContext: anonymous is forbidden.
        /// </summary>
        internal static string WrongSecurityContextAnonymous {
            get {
                return ResourceManager.GetString("WrongSecurityContextAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong credentials format: the received UserPrincipal contains an &apos;at&apos; sign:{0}..
        /// </summary>
        internal static string WrongUserPrincipalFormatMessage {
            get {
                return ResourceManager.GetString("WrongUserPrincipalFormatMessage", resourceCulture);
            }
        }
    }
}
