//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Vestalis.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cotecna.Vestalis.Core.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application administrator.
        /// </summary>
        internal static string ApplicationAdministrator {
            get {
                return ResourceManager.GetString("ApplicationAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned roles.
        /// </summary>
        internal static string AssignedRoles {
            get {
                return ResourceManager.GetString("AssignedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business application.
        /// </summary>
        internal static string BusinessApplication {
            get {
                return ResourceManager.GetString("BusinessApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please mark a business application as default..
        /// </summary>
        internal static string BusinessApplicationDefault {
            get {
                return ResourceManager.GetString("BusinessApplicationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business application name.
        /// </summary>
        internal static string BusinessApplicationName {
            get {
                return ResourceManager.GetString("BusinessApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered category alredy exists, please verify your information..
        /// </summary>
        internal static string CatalogueCategoryExists {
            get {
                return ResourceManager.GetString("CatalogueCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current catalogue category cannot be deleted because is being used..
        /// </summary>
        internal static string CatalogueCategoryNonDeleteMessage {
            get {
                return ResourceManager.GetString("CatalogueCategoryNonDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category {0} cannot be deleted because is being used..
        /// </summary>
        internal static string CatalogueCategoryNonDeleteMultipleMessage {
            get {
                return ResourceManager.GetString("CatalogueCategoryNonDeleteMultipleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue name.
        /// </summary>
        internal static string CatalogueName {
            get {
                return ResourceManager.GetString("CatalogueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue Report.
        /// </summary>
        internal static string CatalogueReport {
            get {
                return ResourceManager.GetString("CatalogueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value already exists, please verify your information..
        /// </summary>
        internal static string CatalogueValueExists {
            get {
                return ResourceManager.GetString("CatalogueValueExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current catalogue value cannot be deleted because is being used..
        /// </summary>
        internal static string CatalogueValueNonDeleteMessage {
            get {
                return ResourceManager.GetString("CatalogueValueNonDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} cannot be deleted because is being used..
        /// </summary>
        internal static string CatalogueValueNonDeleteMultipleMessage {
            get {
                return ResourceManager.GetString("CatalogueValueNonDeleteMultipleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue values Report.
        /// </summary>
        internal static string CatalogueValuesReport {
            get {
                return ResourceManager.GetString("CatalogueValuesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string NullOrEmptyValue {
            get {
                return ResourceManager.GetString("NullOrEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished.
        /// </summary>
        internal static string Unpublished {
            get {
                return ResourceManager.GetString("Unpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalidated.
        /// </summary>
        internal static string Unvalidated {
            get {
                return ResourceManager.GetString("Unvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User e-mail.
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exist in the role {0}..
        /// </summary>
        internal static string UserExistInRole {
            get {
                return ResourceManager.GetString("UserExistInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already assigned to this business application..
        /// </summary>
        internal static string UserInBusinessApplication {
            get {
                return ResourceManager.GetString("UserInBusinessApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User report.
        /// </summary>
        internal static string UserReport {
            get {
                return ResourceManager.GetString("UserReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and permissions.
        /// </summary>
        internal static string UsersAndPermissions {
            get {
                return ResourceManager.GetString("UsersAndPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no users in the system..
        /// </summary>
        internal static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        internal static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated.
        /// </summary>
        internal static string Validated {
            get {
                return ResourceManager.GetString("Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
